# Generated by Django 4.1.7 on 2023-02-20 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=5)),
                ('breed', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(19)])),
                ('spayed_neutered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=5)),
                ('is_available', models.BooleanField(default=True)),
                ('vaccinated', models.BooleanField(default=True)),
            ],
        ),
    ]
