# Generated by Django 4.1.7 on 2023-02-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_pets_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='poster',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
